//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Belajar struct {
	Kode       int32 `sql:"primary_key"`
	Keterangan *string
	Time       *time.Time
	Tanggal    *time.Time
	TglAwal    *time.Time
	Saldo      *float64
	SaldoAwal  float64
	Nominatif  float64
	JmlHari    int32
	KodeTes    int32
}
