//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type LembagaLisensiSistem string

const (
	LembagaLisensiSistem_Sewa    LembagaLisensiSistem = "SEWA"
	LembagaLisensiSistem_Nonsewa LembagaLisensiSistem = "NONSEWA"
)

func (e *LembagaLisensiSistem) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "SEWA":
		*e = LembagaLisensiSistem_Sewa
	case "NONSEWA":
		*e = LembagaLisensiSistem_Nonsewa
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for LembagaLisensiSistem enum")
	}

	return nil
}

func (e LembagaLisensiSistem) String() string {
	return string(e)
}
