//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type LembagaTrans struct {
	TransID     string `sql:"primary_key"`
	LembagaID   string
	TglTrans    time.Time
	Modul       string
	ProdukID    string
	SaldoTrans  float64
	MyKodeTrans int8
	Keterangan  string
}
