//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MyanggotaViewRek struct {
	Modul         string
	NoRekening    string
	NamaAnggota   *string
	Alamat        *string
	NoHp          *string
	KodeLembaga   *string
	NamaLembaga   *string
	URLLembaga    *string
	StatusLembaga *int32
	StatusMobile  *bool
	StatusData    bool
	Saring        *string
}
