//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MyanggotaTrans struct {
	KodeRek    string `sql:"primary_key"`
	NoRekening string
	Modul      string
	KdLembaga  string
	NoHp       string
	StatusData bool
}
