//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Myanggota struct {
	NoHp         string `sql:"primary_key"`
	NoImei       string
	KdReferal    string
	NamaAnggota  string
	NoIdentitas  string
	Alamat       string
	Password     string
	TglReg       time.Time
	StatusMobile bool
}
