//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Mysekolah struct {
	Username    string `sql:"primary_key"`
	KdReferal   string
	Nama        string
	NoIdentitas string
	Alamat      string
	Jkelamin    string
	Password    string
	Email       string
	TglReg      time.Time
	Status      MysekolahStatus
	Keterangan  string
	FotoProfile string
}
