//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type MysekolahStatus string

const (
	MysekolahStatus_Reg    MysekolahStatus = "REG"
	MysekolahStatus_Aktif  MysekolahStatus = "AKTIF"
	MysekolahStatus_Blokir MysekolahStatus = "BLOKIR"
)

func (e *MysekolahStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "REG":
		*e = MysekolahStatus_Reg
	case "AKTIF":
		*e = MysekolahStatus_Aktif
	case "BLOKIR":
		*e = MysekolahStatus_Blokir
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for MysekolahStatus enum")
	}

	return nil
}

func (e MysekolahStatus) String() string {
	return string(e)
}
