//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MysekolahTrans struct {
	Username    string `sql:"primary_key"`
	Nis         string `sql:"primary_key"`
	Nama        string
	KdLembaga   string
	Namalembaga string
	Deskripsi   string
	StatusData  bool
}
