//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PengajuanAktif struct {
	KodePengajuan    string `sql:"primary_key"`
	TglPengajuan     time.Time
	NoHp             string
	Keterangan       string
	Nominal          float64
	NominalDisetujui float64
	KdLembaga        string
	KdCabang         string
	NoAnggota        string
	NoRekening       string
	StatusPengajuan  bool
}
