//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PesanInformasi struct {
	TglPesan    time.Time `sql:"primary_key"`
	Pesan       string
	VersiUpdate string
	Status      bool
	Waktu       int8
}
