//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SimkoChecking struct {
	KodeNasabah    string `sql:"primary_key"`
	KodeLembaga    string
	NasabahID      string
	NamaNasabah    string
	AlamatNasabah  string
	NoHp           string
	JenisIdentitas string
	NoIdentitas    string
	KodeCabang     string
}
