//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TbUser struct {
	ID                 int32 `sql:"primary_key"`
	FirstName          string
	LastName           string
	Username           string `sql:"primary_key"`
	Password           string
	Email              string
	KodeCab            string
	KodeAo             string
	KodePerk           string
	Status             *TbUserStatus
	IDGroup            int32
	AksesDekstop       bool
	AksesWebsite       bool
	AksesMobile        bool
	ChangeLastPassword time.Time
	TglInsert          time.Time
	LastLogin          time.Time
	Cookie             *string
	LimitPengeluaran   float64
	StatusLimit        bool
}
