//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type TbUserStatus string

const (
	TbUserStatus_Active   TbUserStatus = "ACTIVE"
	TbUserStatus_Inactive TbUserStatus = "INACTIVE"
)

func (e *TbUserStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "ACTIVE":
		*e = TbUserStatus_Active
	case "INACTIVE":
		*e = TbUserStatus_Inactive
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for TbUserStatus enum")
	}

	return nil
}

func (e TbUserStatus) String() string {
	return string(e)
}
