//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TransTerakhir struct {
	TglTrans time.Time
	Modul    string
	NoUrut   int32
	KodeCab  string
}
