//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TransBayar struct {
	Transid    int32 `sql:"primary_key"`
	Tanggal    time.Time
	MemberID   string
	Bank       string
	Bayar      int32
	Keterangan string
}
