//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type VaBniKey struct {
	ClientID    string `sql:"primary_key"`
	Prefix      string
	SecretKey   string
	URLAPI      string
	KodeLembaga string
	NamaLembaga string
	URLLembaga  string
	KodeCabRek  string
	MinTrx      float64
	KodePerk    string
}
