//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type VaTransHistory struct {
	TrxID           string `sql:"primary_key"`
	Prefix          string
	ClientID        string
	Vendor          string
	TrxAmount       float64
	PaymentAmount   float64
	BillingType     string
	DatetimeCreate  time.Time
	DatetimeExpired string
	VirtualAccount  string
	CustomerName    string
	CustomerPhone   string
	Modul           string
	NoRekening      string
	KodeCab         string
	NasabahID       string
	StatusVa        string
}
