//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ViewProsesServer struct {
	ID           int64
	User         string
	Host         string
	Db           *string
	Command      string
	Time         int32
	State        *string
	Info         *string
	TimeMs       float64
	Stage        int8
	MaxStage     int8
	Progress     float64
	MemoryUsed   int64
	ExaminedRows int32
	QueryID      int64
	InfoBinary   *[]byte
	Tid          int64
}
