//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ViewDataNasabah struct {
	NamaLembaga    *string
	KodeNasabah    string
	KodeLembaga    string
	NasabahID      string
	NamaNasabah    string
	AlamatNasabah  string
	JenisIdentitas string
	NoIdentitas    string
	KodeCabang     string
	URLLembaga     *string
	ClientService  *string
	AuthKey        *string
	ContentType    *string
}
