//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type WhatsappHistory struct {
	ID          string `sql:"primary_key"`
	Phone       string
	Text        string
	Status      string
	KodeLembaga string
	Tanggal     time.Time
	Jam         time.Time
	Modul       string
	KodeCabang  string
	Mystatus    int32
}
