//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type WhatsappTokenLembaga struct {
	KodeLembaga string `sql:"primary_key"`
	NoWhatsapp  string
	Token       string
	URL         string
	StatusAktif int8
}
