//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type WhatsappToken struct {
	StatusAktif bool `sql:"primary_key"`
	NoWhatsapp  string
	Token       string
	URL         string
}
