//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ZLembagaWhatsappProvider struct {
	Name    string
	URL     string
	Method  string
	Content string
	Data    string
	Header  string
}
