//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Belajar = newBelajarTable("simko_data", "belajar", "")

type belajarTable struct {
	mysql.Table

	// Columns
	Kode       mysql.ColumnInteger
	Keterangan mysql.ColumnString
	Time       mysql.ColumnTimestamp
	Tanggal    mysql.ColumnDate
	TglAwal    mysql.ColumnDate
	Saldo      mysql.ColumnFloat
	SaldoAwal  mysql.ColumnFloat
	Nominatif  mysql.ColumnFloat
	JmlHari    mysql.ColumnInteger
	KodeTes    mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type BelajarTable struct {
	belajarTable

	NEW belajarTable
}

// AS creates new BelajarTable with assigned alias
func (a BelajarTable) AS(alias string) *BelajarTable {
	return newBelajarTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BelajarTable with assigned schema name
func (a BelajarTable) FromSchema(schemaName string) *BelajarTable {
	return newBelajarTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BelajarTable with assigned table prefix
func (a BelajarTable) WithPrefix(prefix string) *BelajarTable {
	return newBelajarTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BelajarTable with assigned table suffix
func (a BelajarTable) WithSuffix(suffix string) *BelajarTable {
	return newBelajarTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBelajarTable(schemaName, tableName, alias string) *BelajarTable {
	return &BelajarTable{
		belajarTable: newBelajarTableImpl(schemaName, tableName, alias),
		NEW:          newBelajarTableImpl("", "new", ""),
	}
}

func newBelajarTableImpl(schemaName, tableName, alias string) belajarTable {
	var (
		KodeColumn       = mysql.IntegerColumn("kode")
		KeteranganColumn = mysql.StringColumn("keterangan")
		TimeColumn       = mysql.TimestampColumn("time")
		TanggalColumn    = mysql.DateColumn("tanggal")
		TglAwalColumn    = mysql.DateColumn("tgl_awal")
		SaldoColumn      = mysql.FloatColumn("saldo")
		SaldoAwalColumn  = mysql.FloatColumn("saldo_awal")
		NominatifColumn  = mysql.FloatColumn("nominatif")
		JmlHariColumn    = mysql.IntegerColumn("jml_hari")
		KodeTesColumn    = mysql.IntegerColumn("kode tes")
		allColumns       = mysql.ColumnList{KodeColumn, KeteranganColumn, TimeColumn, TanggalColumn, TglAwalColumn, SaldoColumn, SaldoAwalColumn, NominatifColumn, JmlHariColumn, KodeTesColumn}
		mutableColumns   = mysql.ColumnList{KeteranganColumn, TimeColumn, TanggalColumn, TglAwalColumn, SaldoColumn, SaldoAwalColumn, NominatifColumn, JmlHariColumn, KodeTesColumn}
	)

	return belajarTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Kode:       KodeColumn,
		Keterangan: KeteranganColumn,
		Time:       TimeColumn,
		Tanggal:    TanggalColumn,
		TglAwal:    TglAwalColumn,
		Saldo:      SaldoColumn,
		SaldoAwal:  SaldoAwalColumn,
		Nominatif:  NominatifColumn,
		JmlHari:    JmlHariColumn,
		KodeTes:    KodeTesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
