//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var DaftarProduk = newDaftarProdukTable("simko_data", "daftar_produk", "")

type daftarProdukTable struct {
	mysql.Table

	// Columns
	KdProduk   mysql.ColumnString
	NamaProduk mysql.ColumnString
	Harga      mysql.ColumnFloat
	Kuota      mysql.ColumnInteger
	MasaAktif  mysql.ColumnInteger
	Jenis      mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type DaftarProdukTable struct {
	daftarProdukTable

	NEW daftarProdukTable
}

// AS creates new DaftarProdukTable with assigned alias
func (a DaftarProdukTable) AS(alias string) *DaftarProdukTable {
	return newDaftarProdukTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DaftarProdukTable with assigned schema name
func (a DaftarProdukTable) FromSchema(schemaName string) *DaftarProdukTable {
	return newDaftarProdukTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DaftarProdukTable with assigned table prefix
func (a DaftarProdukTable) WithPrefix(prefix string) *DaftarProdukTable {
	return newDaftarProdukTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DaftarProdukTable with assigned table suffix
func (a DaftarProdukTable) WithSuffix(suffix string) *DaftarProdukTable {
	return newDaftarProdukTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDaftarProdukTable(schemaName, tableName, alias string) *DaftarProdukTable {
	return &DaftarProdukTable{
		daftarProdukTable: newDaftarProdukTableImpl(schemaName, tableName, alias),
		NEW:               newDaftarProdukTableImpl("", "new", ""),
	}
}

func newDaftarProdukTableImpl(schemaName, tableName, alias string) daftarProdukTable {
	var (
		KdProdukColumn   = mysql.StringColumn("kd_produk")
		NamaProdukColumn = mysql.StringColumn("nama_produk")
		HargaColumn      = mysql.FloatColumn("harga")
		KuotaColumn      = mysql.IntegerColumn("kuota")
		MasaAktifColumn  = mysql.IntegerColumn("masa_aktif")
		JenisColumn      = mysql.StringColumn("jenis")
		allColumns       = mysql.ColumnList{KdProdukColumn, NamaProdukColumn, HargaColumn, KuotaColumn, MasaAktifColumn, JenisColumn}
		mutableColumns   = mysql.ColumnList{NamaProdukColumn, HargaColumn, KuotaColumn, MasaAktifColumn, JenisColumn}
	)

	return daftarProdukTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		KdProduk:   KdProdukColumn,
		NamaProduk: NamaProdukColumn,
		Harga:      HargaColumn,
		Kuota:      KuotaColumn,
		MasaAktif:  MasaAktifColumn,
		Jenis:      JenisColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
