//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Lembaga = newLembagaTable("simko_data", "lembaga", "")

type lembagaTable struct {
	mysql.Table

	// Columns
	Memberid            mysql.ColumnString
	Jenis               mysql.ColumnString
	Nama                mysql.ColumnString
	Alamat              mysql.ColumnString
	Kota                mysql.ColumnString
	Email               mysql.ColumnString
	TglMasuk            mysql.ColumnDate
	Manager             mysql.ColumnString
	Telp                mysql.ColumnString
	Db                  mysql.ColumnString
	Web                 mysql.ColumnString
	URLLembaga          mysql.ColumnString
	ClientService       mysql.ColumnString
	AuthKey             mysql.ColumnString
	ContentType         mysql.ColumnString
	Aktif               mysql.ColumnInteger
	Whatsapp            mysql.ColumnInteger
	ModeWa              mysql.ColumnString
	IjinkanSmsTag       mysql.ColumnBool
	IjinkanHapusMundur  mysql.ColumnBool
	UpdateProgramKhusus mysql.ColumnBool
	BmtcheckingJepara   mysql.ColumnBool
	ServerWhatsapp      mysql.ColumnString
	ServerOtp           mysql.ColumnString
	LisensiSistem       mysql.ColumnString
	TglExpSistem        mysql.ColumnDate
	TglExpWa            mysql.ColumnDate
	TglExpSms           mysql.ColumnDate
	KuotaAwalWa         mysql.ColumnInteger
	KuotaTransWa        mysql.ColumnInteger
	KuotaAkhirWa        mysql.ColumnInteger
	KuotaAwalSms        mysql.ColumnInteger
	KuotaTransSms       mysql.ColumnInteger
	KuotaAkhirSms       mysql.ColumnInteger
	PaketSistem         mysql.ColumnString
	PaketWa             mysql.ColumnString
	PaketSms            mysql.ColumnString
	IjinkanTransMundur  mysql.ColumnString
	SmsStatus           mysql.ColumnInteger
	SmsServer           mysql.ColumnString
	ApikeyWadoh         mysql.ColumnString
	ApikeyCab           mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type LembagaTable struct {
	lembagaTable

	NEW lembagaTable
}

// AS creates new LembagaTable with assigned alias
func (a LembagaTable) AS(alias string) *LembagaTable {
	return newLembagaTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LembagaTable with assigned schema name
func (a LembagaTable) FromSchema(schemaName string) *LembagaTable {
	return newLembagaTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LembagaTable with assigned table prefix
func (a LembagaTable) WithPrefix(prefix string) *LembagaTable {
	return newLembagaTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LembagaTable with assigned table suffix
func (a LembagaTable) WithSuffix(suffix string) *LembagaTable {
	return newLembagaTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLembagaTable(schemaName, tableName, alias string) *LembagaTable {
	return &LembagaTable{
		lembagaTable: newLembagaTableImpl(schemaName, tableName, alias),
		NEW:          newLembagaTableImpl("", "new", ""),
	}
}

func newLembagaTableImpl(schemaName, tableName, alias string) lembagaTable {
	var (
		MemberidColumn            = mysql.StringColumn("memberid")
		JenisColumn               = mysql.StringColumn("jenis")
		NamaColumn                = mysql.StringColumn("nama")
		AlamatColumn              = mysql.StringColumn("alamat")
		KotaColumn                = mysql.StringColumn("kota")
		EmailColumn               = mysql.StringColumn("email")
		TglMasukColumn            = mysql.DateColumn("tgl_masuk")
		ManagerColumn             = mysql.StringColumn("Manager")
		TelpColumn                = mysql.StringColumn("telp")
		DbColumn                  = mysql.StringColumn("db")
		WebColumn                 = mysql.StringColumn("web")
		URLLembagaColumn          = mysql.StringColumn("url_lembaga")
		ClientServiceColumn       = mysql.StringColumn("CLIENT_SERVICE")
		AuthKeyColumn             = mysql.StringColumn("AUTH_KEY")
		ContentTypeColumn         = mysql.StringColumn("CONTENT_TYPE")
		AktifColumn               = mysql.IntegerColumn("aktif")
		WhatsappColumn            = mysql.IntegerColumn("whatsapp")
		ModeWaColumn              = mysql.StringColumn("mode_wa")
		IjinkanSmsTagColumn       = mysql.BoolColumn("ijinkan_sms_tag")
		IjinkanHapusMundurColumn  = mysql.BoolColumn("ijinkan_hapus_mundur")
		UpdateProgramKhususColumn = mysql.BoolColumn("update_program_khusus")
		BmtcheckingJeparaColumn   = mysql.BoolColumn("bmtchecking_jepara")
		ServerWhatsappColumn      = mysql.StringColumn("server_whatsapp")
		ServerOtpColumn           = mysql.StringColumn("server_otp")
		LisensiSistemColumn       = mysql.StringColumn("lisensi_sistem")
		TglExpSistemColumn        = mysql.DateColumn("tgl_exp_sistem")
		TglExpWaColumn            = mysql.DateColumn("tgl_exp_wa")
		TglExpSmsColumn           = mysql.DateColumn("tgl_exp_sms")
		KuotaAwalWaColumn         = mysql.IntegerColumn("kuota_awal_wa")
		KuotaTransWaColumn        = mysql.IntegerColumn("kuota_trans_wa")
		KuotaAkhirWaColumn        = mysql.IntegerColumn("kuota_akhir_wa")
		KuotaAwalSmsColumn        = mysql.IntegerColumn("kuota_awal_sms")
		KuotaTransSmsColumn       = mysql.IntegerColumn("kuota_trans_sms")
		KuotaAkhirSmsColumn       = mysql.IntegerColumn("kuota_akhir_sms")
		PaketSistemColumn         = mysql.StringColumn("paket_sistem")
		PaketWaColumn             = mysql.StringColumn("paket_wa")
		PaketSmsColumn            = mysql.StringColumn("paket_sms")
		IjinkanTransMundurColumn  = mysql.StringColumn("ijinkan_trans_mundur")
		SmsStatusColumn           = mysql.IntegerColumn("sms_status")
		SmsServerColumn           = mysql.StringColumn("sms_server")
		ApikeyWadohColumn         = mysql.StringColumn("apikey_wadoh")
		ApikeyCabColumn           = mysql.StringColumn("apikey_cab")
		allColumns                = mysql.ColumnList{MemberidColumn, JenisColumn, NamaColumn, AlamatColumn, KotaColumn, EmailColumn, TglMasukColumn, ManagerColumn, TelpColumn, DbColumn, WebColumn, URLLembagaColumn, ClientServiceColumn, AuthKeyColumn, ContentTypeColumn, AktifColumn, WhatsappColumn, ModeWaColumn, IjinkanSmsTagColumn, IjinkanHapusMundurColumn, UpdateProgramKhususColumn, BmtcheckingJeparaColumn, ServerWhatsappColumn, ServerOtpColumn, LisensiSistemColumn, TglExpSistemColumn, TglExpWaColumn, TglExpSmsColumn, KuotaAwalWaColumn, KuotaTransWaColumn, KuotaAkhirWaColumn, KuotaAwalSmsColumn, KuotaTransSmsColumn, KuotaAkhirSmsColumn, PaketSistemColumn, PaketWaColumn, PaketSmsColumn, IjinkanTransMundurColumn, SmsStatusColumn, SmsServerColumn, ApikeyWadohColumn, ApikeyCabColumn}
		mutableColumns            = mysql.ColumnList{JenisColumn, NamaColumn, AlamatColumn, KotaColumn, EmailColumn, TglMasukColumn, ManagerColumn, TelpColumn, DbColumn, WebColumn, URLLembagaColumn, ClientServiceColumn, AuthKeyColumn, ContentTypeColumn, AktifColumn, WhatsappColumn, ModeWaColumn, IjinkanSmsTagColumn, IjinkanHapusMundurColumn, UpdateProgramKhususColumn, BmtcheckingJeparaColumn, ServerWhatsappColumn, ServerOtpColumn, LisensiSistemColumn, TglExpSistemColumn, TglExpWaColumn, TglExpSmsColumn, KuotaAwalWaColumn, KuotaTransWaColumn, KuotaAkhirWaColumn, KuotaAwalSmsColumn, KuotaTransSmsColumn, KuotaAkhirSmsColumn, PaketSistemColumn, PaketWaColumn, PaketSmsColumn, IjinkanTransMundurColumn, SmsStatusColumn, SmsServerColumn, ApikeyWadohColumn, ApikeyCabColumn}
	)

	return lembagaTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Memberid:            MemberidColumn,
		Jenis:               JenisColumn,
		Nama:                NamaColumn,
		Alamat:              AlamatColumn,
		Kota:                KotaColumn,
		Email:               EmailColumn,
		TglMasuk:            TglMasukColumn,
		Manager:             ManagerColumn,
		Telp:                TelpColumn,
		Db:                  DbColumn,
		Web:                 WebColumn,
		URLLembaga:          URLLembagaColumn,
		ClientService:       ClientServiceColumn,
		AuthKey:             AuthKeyColumn,
		ContentType:         ContentTypeColumn,
		Aktif:               AktifColumn,
		Whatsapp:            WhatsappColumn,
		ModeWa:              ModeWaColumn,
		IjinkanSmsTag:       IjinkanSmsTagColumn,
		IjinkanHapusMundur:  IjinkanHapusMundurColumn,
		UpdateProgramKhusus: UpdateProgramKhususColumn,
		BmtcheckingJepara:   BmtcheckingJeparaColumn,
		ServerWhatsapp:      ServerWhatsappColumn,
		ServerOtp:           ServerOtpColumn,
		LisensiSistem:       LisensiSistemColumn,
		TglExpSistem:        TglExpSistemColumn,
		TglExpWa:            TglExpWaColumn,
		TglExpSms:           TglExpSmsColumn,
		KuotaAwalWa:         KuotaAwalWaColumn,
		KuotaTransWa:        KuotaTransWaColumn,
		KuotaAkhirWa:        KuotaAkhirWaColumn,
		KuotaAwalSms:        KuotaAwalSmsColumn,
		KuotaTransSms:       KuotaTransSmsColumn,
		KuotaAkhirSms:       KuotaAkhirSmsColumn,
		PaketSistem:         PaketSistemColumn,
		PaketWa:             PaketWaColumn,
		PaketSms:            PaketSmsColumn,
		IjinkanTransMundur:  IjinkanTransMundurColumn,
		SmsStatus:           SmsStatusColumn,
		SmsServer:           SmsServerColumn,
		ApikeyWadoh:         ApikeyWadohColumn,
		ApikeyCab:           ApikeyCabColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
