//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var LembagaTrans = newLembagaTransTable("simko_data", "lembaga_trans", "")

type lembagaTransTable struct {
	mysql.Table

	// Columns
	TransID     mysql.ColumnString
	LembagaID   mysql.ColumnString
	TglTrans    mysql.ColumnDate
	Modul       mysql.ColumnString
	ProdukID    mysql.ColumnString
	SaldoTrans  mysql.ColumnFloat
	MyKodeTrans mysql.ColumnInteger
	Keterangan  mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type LembagaTransTable struct {
	lembagaTransTable

	NEW lembagaTransTable
}

// AS creates new LembagaTransTable with assigned alias
func (a LembagaTransTable) AS(alias string) *LembagaTransTable {
	return newLembagaTransTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LembagaTransTable with assigned schema name
func (a LembagaTransTable) FromSchema(schemaName string) *LembagaTransTable {
	return newLembagaTransTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LembagaTransTable with assigned table prefix
func (a LembagaTransTable) WithPrefix(prefix string) *LembagaTransTable {
	return newLembagaTransTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LembagaTransTable with assigned table suffix
func (a LembagaTransTable) WithSuffix(suffix string) *LembagaTransTable {
	return newLembagaTransTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLembagaTransTable(schemaName, tableName, alias string) *LembagaTransTable {
	return &LembagaTransTable{
		lembagaTransTable: newLembagaTransTableImpl(schemaName, tableName, alias),
		NEW:               newLembagaTransTableImpl("", "new", ""),
	}
}

func newLembagaTransTableImpl(schemaName, tableName, alias string) lembagaTransTable {
	var (
		TransIDColumn     = mysql.StringColumn("trans_id")
		LembagaIDColumn   = mysql.StringColumn("lembaga_id")
		TglTransColumn    = mysql.DateColumn("tgl_trans")
		ModulColumn       = mysql.StringColumn("modul")
		ProdukIDColumn    = mysql.StringColumn("produk_id")
		SaldoTransColumn  = mysql.FloatColumn("saldo_trans")
		MyKodeTransColumn = mysql.IntegerColumn("my_kode_trans")
		KeteranganColumn  = mysql.StringColumn("keterangan")
		allColumns        = mysql.ColumnList{TransIDColumn, LembagaIDColumn, TglTransColumn, ModulColumn, ProdukIDColumn, SaldoTransColumn, MyKodeTransColumn, KeteranganColumn}
		mutableColumns    = mysql.ColumnList{LembagaIDColumn, TglTransColumn, ModulColumn, ProdukIDColumn, SaldoTransColumn, MyKodeTransColumn, KeteranganColumn}
	)

	return lembagaTransTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TransID:     TransIDColumn,
		LembagaID:   LembagaIDColumn,
		TglTrans:    TglTransColumn,
		Modul:       ModulColumn,
		ProdukID:    ProdukIDColumn,
		SaldoTrans:  SaldoTransColumn,
		MyKodeTrans: MyKodeTransColumn,
		Keterangan:  KeteranganColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
