//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var MyanggotaLogins = newMyanggotaLoginsTable("simko_data", "myanggota_logins", "")

type myanggotaLoginsTable struct {
	mysql.Table

	// Columns
	ID              mysql.ColumnInteger
	Phone           mysql.ColumnString
	RegistrationID  mysql.ColumnString
	CryptedPassword mysql.ColumnString
	CryptedPin      mysql.ColumnString
	CreatedAt       mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type MyanggotaLoginsTable struct {
	myanggotaLoginsTable

	NEW myanggotaLoginsTable
}

// AS creates new MyanggotaLoginsTable with assigned alias
func (a MyanggotaLoginsTable) AS(alias string) *MyanggotaLoginsTable {
	return newMyanggotaLoginsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MyanggotaLoginsTable with assigned schema name
func (a MyanggotaLoginsTable) FromSchema(schemaName string) *MyanggotaLoginsTable {
	return newMyanggotaLoginsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MyanggotaLoginsTable with assigned table prefix
func (a MyanggotaLoginsTable) WithPrefix(prefix string) *MyanggotaLoginsTable {
	return newMyanggotaLoginsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MyanggotaLoginsTable with assigned table suffix
func (a MyanggotaLoginsTable) WithSuffix(suffix string) *MyanggotaLoginsTable {
	return newMyanggotaLoginsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMyanggotaLoginsTable(schemaName, tableName, alias string) *MyanggotaLoginsTable {
	return &MyanggotaLoginsTable{
		myanggotaLoginsTable: newMyanggotaLoginsTableImpl(schemaName, tableName, alias),
		NEW:                  newMyanggotaLoginsTableImpl("", "new", ""),
	}
}

func newMyanggotaLoginsTableImpl(schemaName, tableName, alias string) myanggotaLoginsTable {
	var (
		IDColumn              = mysql.IntegerColumn("id")
		PhoneColumn           = mysql.StringColumn("phone")
		RegistrationIDColumn  = mysql.StringColumn("registration_id")
		CryptedPasswordColumn = mysql.StringColumn("crypted_password")
		CryptedPinColumn      = mysql.StringColumn("crypted_pin")
		CreatedAtColumn       = mysql.TimestampColumn("created_at")
		allColumns            = mysql.ColumnList{IDColumn, PhoneColumn, RegistrationIDColumn, CryptedPasswordColumn, CryptedPinColumn, CreatedAtColumn}
		mutableColumns        = mysql.ColumnList{PhoneColumn, RegistrationIDColumn, CryptedPasswordColumn, CryptedPinColumn, CreatedAtColumn}
	)

	return myanggotaLoginsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		Phone:           PhoneColumn,
		RegistrationID:  RegistrationIDColumn,
		CryptedPassword: CryptedPasswordColumn,
		CryptedPin:      CryptedPinColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
