//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Myanggota = newMyanggotaTable("simko_data", "myanggota", "")

type myanggotaTable struct {
	mysql.Table

	// Columns
	NoHp         mysql.ColumnString
	NoImei       mysql.ColumnString
	KdReferal    mysql.ColumnString
	NamaAnggota  mysql.ColumnString
	NoIdentitas  mysql.ColumnString
	Alamat       mysql.ColumnString
	Password     mysql.ColumnString
	TglReg       mysql.ColumnDate
	StatusMobile mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type MyanggotaTable struct {
	myanggotaTable

	NEW myanggotaTable
}

// AS creates new MyanggotaTable with assigned alias
func (a MyanggotaTable) AS(alias string) *MyanggotaTable {
	return newMyanggotaTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MyanggotaTable with assigned schema name
func (a MyanggotaTable) FromSchema(schemaName string) *MyanggotaTable {
	return newMyanggotaTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MyanggotaTable with assigned table prefix
func (a MyanggotaTable) WithPrefix(prefix string) *MyanggotaTable {
	return newMyanggotaTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MyanggotaTable with assigned table suffix
func (a MyanggotaTable) WithSuffix(suffix string) *MyanggotaTable {
	return newMyanggotaTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMyanggotaTable(schemaName, tableName, alias string) *MyanggotaTable {
	return &MyanggotaTable{
		myanggotaTable: newMyanggotaTableImpl(schemaName, tableName, alias),
		NEW:            newMyanggotaTableImpl("", "new", ""),
	}
}

func newMyanggotaTableImpl(schemaName, tableName, alias string) myanggotaTable {
	var (
		NoHpColumn         = mysql.StringColumn("no_hp")
		NoImeiColumn       = mysql.StringColumn("no_imei")
		KdReferalColumn    = mysql.StringColumn("kd_referal")
		NamaAnggotaColumn  = mysql.StringColumn("nama_anggota")
		NoIdentitasColumn  = mysql.StringColumn("no_identitas")
		AlamatColumn       = mysql.StringColumn("alamat")
		PasswordColumn     = mysql.StringColumn("password")
		TglRegColumn       = mysql.DateColumn("tgl_reg")
		StatusMobileColumn = mysql.BoolColumn("status_mobile")
		allColumns         = mysql.ColumnList{NoHpColumn, NoImeiColumn, KdReferalColumn, NamaAnggotaColumn, NoIdentitasColumn, AlamatColumn, PasswordColumn, TglRegColumn, StatusMobileColumn}
		mutableColumns     = mysql.ColumnList{NoImeiColumn, KdReferalColumn, NamaAnggotaColumn, NoIdentitasColumn, AlamatColumn, PasswordColumn, TglRegColumn, StatusMobileColumn}
	)

	return myanggotaTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		NoHp:         NoHpColumn,
		NoImei:       NoImeiColumn,
		KdReferal:    KdReferalColumn,
		NamaAnggota:  NamaAnggotaColumn,
		NoIdentitas:  NoIdentitasColumn,
		Alamat:       AlamatColumn,
		Password:     PasswordColumn,
		TglReg:       TglRegColumn,
		StatusMobile: StatusMobileColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
