//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var PesanInformasi = newPesanInformasiTable("simko_data", "pesan_informasi", "")

type pesanInformasiTable struct {
	mysql.Table

	// Columns
	TglPesan    mysql.ColumnDate
	Pesan       mysql.ColumnString
	VersiUpdate mysql.ColumnString
	Status      mysql.ColumnBool
	Waktu       mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type PesanInformasiTable struct {
	pesanInformasiTable

	NEW pesanInformasiTable
}

// AS creates new PesanInformasiTable with assigned alias
func (a PesanInformasiTable) AS(alias string) *PesanInformasiTable {
	return newPesanInformasiTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PesanInformasiTable with assigned schema name
func (a PesanInformasiTable) FromSchema(schemaName string) *PesanInformasiTable {
	return newPesanInformasiTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PesanInformasiTable with assigned table prefix
func (a PesanInformasiTable) WithPrefix(prefix string) *PesanInformasiTable {
	return newPesanInformasiTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PesanInformasiTable with assigned table suffix
func (a PesanInformasiTable) WithSuffix(suffix string) *PesanInformasiTable {
	return newPesanInformasiTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPesanInformasiTable(schemaName, tableName, alias string) *PesanInformasiTable {
	return &PesanInformasiTable{
		pesanInformasiTable: newPesanInformasiTableImpl(schemaName, tableName, alias),
		NEW:                 newPesanInformasiTableImpl("", "new", ""),
	}
}

func newPesanInformasiTableImpl(schemaName, tableName, alias string) pesanInformasiTable {
	var (
		TglPesanColumn    = mysql.DateColumn("tgl_pesan")
		PesanColumn       = mysql.StringColumn("pesan")
		VersiUpdateColumn = mysql.StringColumn("versi_update")
		StatusColumn      = mysql.BoolColumn("status")
		WaktuColumn       = mysql.IntegerColumn("waktu")
		allColumns        = mysql.ColumnList{TglPesanColumn, PesanColumn, VersiUpdateColumn, StatusColumn, WaktuColumn}
		mutableColumns    = mysql.ColumnList{PesanColumn, VersiUpdateColumn, StatusColumn, WaktuColumn}
	)

	return pesanInformasiTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TglPesan:    TglPesanColumn,
		Pesan:       PesanColumn,
		VersiUpdate: VersiUpdateColumn,
		Status:      StatusColumn,
		Waktu:       WaktuColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
