//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Belajar = Belajar.FromSchema(schema)
	DaftarProduk = DaftarProduk.FromSchema(schema)
	Lembaga = Lembaga.FromSchema(schema)
	LembagaTrans = LembagaTrans.FromSchema(schema)
	LinkUpdate = LinkUpdate.FromSchema(schema)
	Logger = Logger.FromSchema(schema)
	Myanggota = Myanggota.FromSchema(schema)
	MyanggotaConnects = MyanggotaConnects.FromSchema(schema)
	MyanggotaLogins = MyanggotaLogins.FromSchema(schema)
	MyanggotaRefreshTokens = MyanggotaRefreshTokens.FromSchema(schema)
	MyanggotaScrambles = MyanggotaScrambles.FromSchema(schema)
	MyanggotaTrans = MyanggotaTrans.FromSchema(schema)
	MyanggotaWhatsappIn = MyanggotaWhatsappIn.FromSchema(schema)
	Mysekolah = Mysekolah.FromSchema(schema)
	MysekolahTrans = MysekolahTrans.FromSchema(schema)
	PengajuanAktif = PengajuanAktif.FromSchema(schema)
	PesanInformasi = PesanInformasi.FromSchema(schema)
	PortalpulsaCallback = PortalpulsaCallback.FromSchema(schema)
	SimkoChecking = SimkoChecking.FromSchema(schema)
	TbAppConfig = TbAppConfig.FromSchema(schema)
	TbUser = TbUser.FromSchema(schema)
	TbUserAuthentication = TbUserAuthentication.FromSchema(schema)
	TransBayar = TransBayar.FromSchema(schema)
	TransTerakhir = TransTerakhir.FromSchema(schema)
	VaBniKey = VaBniKey.FromSchema(schema)
	VaHistoryCb = VaHistoryCb.FromSchema(schema)
	VaTransHistory = VaTransHistory.FromSchema(schema)
	WhatsappBlokir = WhatsappBlokir.FromSchema(schema)
	WhatsappHistory = WhatsappHistory.FromSchema(schema)
	WhatsappToken = WhatsappToken.FromSchema(schema)
	WhatsappTokenAtlantic = WhatsappTokenAtlantic.FromSchema(schema)
	WhatsappTokenLembaga = WhatsappTokenLembaga.FromSchema(schema)
	ZLembagaWhatsapp = ZLembagaWhatsapp.FromSchema(schema)
	ZLembagaWhatsappProvider = ZLembagaWhatsappProvider.FromSchema(schema)
}
