//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var VaHistoryCb = newVaHistoryCbTable("simko_data", "va_history_cb", "")

type vaHistoryCbTable struct {
	mysql.Table

	// Columns
	Keterangan mysql.ColumnString
	Tanggal    mysql.ColumnDate
	Jam        mysql.ColumnTime

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type VaHistoryCbTable struct {
	vaHistoryCbTable

	NEW vaHistoryCbTable
}

// AS creates new VaHistoryCbTable with assigned alias
func (a VaHistoryCbTable) AS(alias string) *VaHistoryCbTable {
	return newVaHistoryCbTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new VaHistoryCbTable with assigned schema name
func (a VaHistoryCbTable) FromSchema(schemaName string) *VaHistoryCbTable {
	return newVaHistoryCbTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new VaHistoryCbTable with assigned table prefix
func (a VaHistoryCbTable) WithPrefix(prefix string) *VaHistoryCbTable {
	return newVaHistoryCbTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new VaHistoryCbTable with assigned table suffix
func (a VaHistoryCbTable) WithSuffix(suffix string) *VaHistoryCbTable {
	return newVaHistoryCbTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newVaHistoryCbTable(schemaName, tableName, alias string) *VaHistoryCbTable {
	return &VaHistoryCbTable{
		vaHistoryCbTable: newVaHistoryCbTableImpl(schemaName, tableName, alias),
		NEW:              newVaHistoryCbTableImpl("", "new", ""),
	}
}

func newVaHistoryCbTableImpl(schemaName, tableName, alias string) vaHistoryCbTable {
	var (
		KeteranganColumn = mysql.StringColumn("keterangan")
		TanggalColumn    = mysql.DateColumn("tanggal")
		JamColumn        = mysql.TimeColumn("jam")
		allColumns       = mysql.ColumnList{KeteranganColumn, TanggalColumn, JamColumn}
		mutableColumns   = mysql.ColumnList{KeteranganColumn, TanggalColumn, JamColumn}
	)

	return vaHistoryCbTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Keterangan: KeteranganColumn,
		Tanggal:    TanggalColumn,
		Jam:        JamColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
