//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var VaTransHistory = newVaTransHistoryTable("simko_data", "va_trans_history", "")

type vaTransHistoryTable struct {
	mysql.Table

	// Columns
	TrxID           mysql.ColumnString
	Prefix          mysql.ColumnString
	ClientID        mysql.ColumnString
	Vendor          mysql.ColumnString
	TrxAmount       mysql.ColumnFloat
	PaymentAmount   mysql.ColumnFloat
	BillingType     mysql.ColumnString
	DatetimeCreate  mysql.ColumnTimestamp
	DatetimeExpired mysql.ColumnString
	VirtualAccount  mysql.ColumnString
	CustomerName    mysql.ColumnString
	CustomerPhone   mysql.ColumnString
	Modul           mysql.ColumnString
	NoRekening      mysql.ColumnString
	KodeCab         mysql.ColumnString
	NasabahID       mysql.ColumnString
	StatusVa        mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type VaTransHistoryTable struct {
	vaTransHistoryTable

	NEW vaTransHistoryTable
}

// AS creates new VaTransHistoryTable with assigned alias
func (a VaTransHistoryTable) AS(alias string) *VaTransHistoryTable {
	return newVaTransHistoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new VaTransHistoryTable with assigned schema name
func (a VaTransHistoryTable) FromSchema(schemaName string) *VaTransHistoryTable {
	return newVaTransHistoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new VaTransHistoryTable with assigned table prefix
func (a VaTransHistoryTable) WithPrefix(prefix string) *VaTransHistoryTable {
	return newVaTransHistoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new VaTransHistoryTable with assigned table suffix
func (a VaTransHistoryTable) WithSuffix(suffix string) *VaTransHistoryTable {
	return newVaTransHistoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newVaTransHistoryTable(schemaName, tableName, alias string) *VaTransHistoryTable {
	return &VaTransHistoryTable{
		vaTransHistoryTable: newVaTransHistoryTableImpl(schemaName, tableName, alias),
		NEW:                 newVaTransHistoryTableImpl("", "new", ""),
	}
}

func newVaTransHistoryTableImpl(schemaName, tableName, alias string) vaTransHistoryTable {
	var (
		TrxIDColumn           = mysql.StringColumn("trx_id")
		PrefixColumn          = mysql.StringColumn("Prefix")
		ClientIDColumn        = mysql.StringColumn("Client_Id")
		VendorColumn          = mysql.StringColumn("vendor")
		TrxAmountColumn       = mysql.FloatColumn("trx_amount")
		PaymentAmountColumn   = mysql.FloatColumn("payment_amount")
		BillingTypeColumn     = mysql.StringColumn("billing_type")
		DatetimeCreateColumn  = mysql.TimestampColumn("datetime_create")
		DatetimeExpiredColumn = mysql.StringColumn("datetime_expired")
		VirtualAccountColumn  = mysql.StringColumn("virtual_account")
		CustomerNameColumn    = mysql.StringColumn("customer_name")
		CustomerPhoneColumn   = mysql.StringColumn("customer_phone")
		ModulColumn           = mysql.StringColumn("modul")
		NoRekeningColumn      = mysql.StringColumn("no_rekening")
		KodeCabColumn         = mysql.StringColumn("kode_cab")
		NasabahIDColumn       = mysql.StringColumn("nasabah_id")
		StatusVaColumn        = mysql.StringColumn("status_va")
		allColumns            = mysql.ColumnList{TrxIDColumn, PrefixColumn, ClientIDColumn, VendorColumn, TrxAmountColumn, PaymentAmountColumn, BillingTypeColumn, DatetimeCreateColumn, DatetimeExpiredColumn, VirtualAccountColumn, CustomerNameColumn, CustomerPhoneColumn, ModulColumn, NoRekeningColumn, KodeCabColumn, NasabahIDColumn, StatusVaColumn}
		mutableColumns        = mysql.ColumnList{PrefixColumn, ClientIDColumn, VendorColumn, TrxAmountColumn, PaymentAmountColumn, BillingTypeColumn, DatetimeCreateColumn, DatetimeExpiredColumn, VirtualAccountColumn, CustomerNameColumn, CustomerPhoneColumn, ModulColumn, NoRekeningColumn, KodeCabColumn, NasabahIDColumn, StatusVaColumn}
	)

	return vaTransHistoryTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TrxID:           TrxIDColumn,
		Prefix:          PrefixColumn,
		ClientID:        ClientIDColumn,
		Vendor:          VendorColumn,
		TrxAmount:       TrxAmountColumn,
		PaymentAmount:   PaymentAmountColumn,
		BillingType:     BillingTypeColumn,
		DatetimeCreate:  DatetimeCreateColumn,
		DatetimeExpired: DatetimeExpiredColumn,
		VirtualAccount:  VirtualAccountColumn,
		CustomerName:    CustomerNameColumn,
		CustomerPhone:   CustomerPhoneColumn,
		Modul:           ModulColumn,
		NoRekening:      NoRekeningColumn,
		KodeCab:         KodeCabColumn,
		NasabahID:       NasabahIDColumn,
		StatusVa:        StatusVaColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
