//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var WhatsappHistory = newWhatsappHistoryTable("simko_data", "whatsapp_history", "")

type whatsappHistoryTable struct {
	mysql.Table

	// Columns
	ID          mysql.ColumnString
	Phone       mysql.ColumnString
	Text        mysql.ColumnString
	Status      mysql.ColumnString
	KodeLembaga mysql.ColumnString
	Tanggal     mysql.ColumnDate
	Jam         mysql.ColumnTime
	Modul       mysql.ColumnString
	KodeCabang  mysql.ColumnString
	Mystatus    mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type WhatsappHistoryTable struct {
	whatsappHistoryTable

	NEW whatsappHistoryTable
}

// AS creates new WhatsappHistoryTable with assigned alias
func (a WhatsappHistoryTable) AS(alias string) *WhatsappHistoryTable {
	return newWhatsappHistoryTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WhatsappHistoryTable with assigned schema name
func (a WhatsappHistoryTable) FromSchema(schemaName string) *WhatsappHistoryTable {
	return newWhatsappHistoryTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WhatsappHistoryTable with assigned table prefix
func (a WhatsappHistoryTable) WithPrefix(prefix string) *WhatsappHistoryTable {
	return newWhatsappHistoryTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WhatsappHistoryTable with assigned table suffix
func (a WhatsappHistoryTable) WithSuffix(suffix string) *WhatsappHistoryTable {
	return newWhatsappHistoryTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWhatsappHistoryTable(schemaName, tableName, alias string) *WhatsappHistoryTable {
	return &WhatsappHistoryTable{
		whatsappHistoryTable: newWhatsappHistoryTableImpl(schemaName, tableName, alias),
		NEW:                  newWhatsappHistoryTableImpl("", "new", ""),
	}
}

func newWhatsappHistoryTableImpl(schemaName, tableName, alias string) whatsappHistoryTable {
	var (
		IDColumn          = mysql.StringColumn("id")
		PhoneColumn       = mysql.StringColumn("phone")
		TextColumn        = mysql.StringColumn("text")
		StatusColumn      = mysql.StringColumn("status")
		KodeLembagaColumn = mysql.StringColumn("kode_lembaga")
		TanggalColumn     = mysql.DateColumn("tanggal")
		JamColumn         = mysql.TimeColumn("jam")
		ModulColumn       = mysql.StringColumn("modul")
		KodeCabangColumn  = mysql.StringColumn("kode_cabang")
		MystatusColumn    = mysql.IntegerColumn("mystatus")
		allColumns        = mysql.ColumnList{IDColumn, PhoneColumn, TextColumn, StatusColumn, KodeLembagaColumn, TanggalColumn, JamColumn, ModulColumn, KodeCabangColumn, MystatusColumn}
		mutableColumns    = mysql.ColumnList{PhoneColumn, TextColumn, StatusColumn, KodeLembagaColumn, TanggalColumn, JamColumn, ModulColumn, KodeCabangColumn, MystatusColumn}
	)

	return whatsappHistoryTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Phone:       PhoneColumn,
		Text:        TextColumn,
		Status:      StatusColumn,
		KodeLembaga: KodeLembagaColumn,
		Tanggal:     TanggalColumn,
		Jam:         JamColumn,
		Modul:       ModulColumn,
		KodeCabang:  KodeCabangColumn,
		Mystatus:    MystatusColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
