//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ZLembagaWhatsappProvider = newZLembagaWhatsappProviderTable("simko_data", "z_lembaga_whatsapp_provider", "")

type zLembagaWhatsappProviderTable struct {
	mysql.Table

	// Columns
	Name    mysql.ColumnString
	URL     mysql.ColumnString
	Method  mysql.ColumnString
	Content mysql.ColumnString
	Data    mysql.ColumnString
	Header  mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type ZLembagaWhatsappProviderTable struct {
	zLembagaWhatsappProviderTable

	NEW zLembagaWhatsappProviderTable
}

// AS creates new ZLembagaWhatsappProviderTable with assigned alias
func (a ZLembagaWhatsappProviderTable) AS(alias string) *ZLembagaWhatsappProviderTable {
	return newZLembagaWhatsappProviderTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ZLembagaWhatsappProviderTable with assigned schema name
func (a ZLembagaWhatsappProviderTable) FromSchema(schemaName string) *ZLembagaWhatsappProviderTable {
	return newZLembagaWhatsappProviderTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ZLembagaWhatsappProviderTable with assigned table prefix
func (a ZLembagaWhatsappProviderTable) WithPrefix(prefix string) *ZLembagaWhatsappProviderTable {
	return newZLembagaWhatsappProviderTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ZLembagaWhatsappProviderTable with assigned table suffix
func (a ZLembagaWhatsappProviderTable) WithSuffix(suffix string) *ZLembagaWhatsappProviderTable {
	return newZLembagaWhatsappProviderTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newZLembagaWhatsappProviderTable(schemaName, tableName, alias string) *ZLembagaWhatsappProviderTable {
	return &ZLembagaWhatsappProviderTable{
		zLembagaWhatsappProviderTable: newZLembagaWhatsappProviderTableImpl(schemaName, tableName, alias),
		NEW:                           newZLembagaWhatsappProviderTableImpl("", "new", ""),
	}
}

func newZLembagaWhatsappProviderTableImpl(schemaName, tableName, alias string) zLembagaWhatsappProviderTable {
	var (
		NameColumn     = mysql.StringColumn("name")
		URLColumn      = mysql.StringColumn("url")
		MethodColumn   = mysql.StringColumn("method")
		ContentColumn  = mysql.StringColumn("content")
		DataColumn     = mysql.StringColumn("data")
		HeaderColumn   = mysql.StringColumn("header")
		allColumns     = mysql.ColumnList{NameColumn, URLColumn, MethodColumn, ContentColumn, DataColumn, HeaderColumn}
		mutableColumns = mysql.ColumnList{NameColumn, URLColumn, MethodColumn, ContentColumn, DataColumn, HeaderColumn}
	)

	return zLembagaWhatsappProviderTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Name:    NameColumn,
		URL:     URLColumn,
		Method:  MethodColumn,
		Content: ContentColumn,
		Data:    DataColumn,
		Header:  HeaderColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
