//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AccountAktif string

const (
	AccountAktif_1 AccountAktif = "1"
	AccountAktif_0 AccountAktif = "0"
)

func (e *AccountAktif) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "1":
		*e = AccountAktif_1
	case "0":
		*e = AccountAktif_0
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AccountAktif enum")
	}

	return nil
}

func (e AccountAktif) String() string {
	return string(e)
}
