//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AccountLevel string

const (
	AccountLevel_1 AccountLevel = "1"
	AccountLevel_2 AccountLevel = "2"
)

func (e *AccountLevel) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "1":
		*e = AccountLevel_1
	case "2":
		*e = AccountLevel_2
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AccountLevel enum")
	}

	return nil
}

func (e AccountLevel) String() string {
	return string(e)
}
