//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type AllContactsType string

const (
	AllContactsType_Personal AllContactsType = "Personal"
	AllContactsType_Group    AllContactsType = "Group"
)

func (e *AllContactsType) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "Personal":
		*e = AllContactsType_Personal
	case "Group":
		*e = AllContactsType_Group
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for AllContactsType enum")
	}

	return nil
}

func (e AllContactsType) String() string {
	return string(e)
}
