//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Autoreply struct {
	ID       int32 `sql:"primary_key"`
	Keyword  string
	Response string
	Media    *string
	Nomor    string
	MakeBy   string
}
