//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Device struct {
	ID          int32 `sql:"primary_key"`
	Pemilik     string
	Nomor       string
	LinkWebhook string
	Aktif       DeviceAktif
}
