//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type DeviceAktif string

const (
	DeviceAktif_1 DeviceAktif = "1"
	DeviceAktif_0 DeviceAktif = "0"
)

func (e *DeviceAktif) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "1":
		*e = DeviceAktif_1
	case "0":
		*e = DeviceAktif_0
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for DeviceAktif enum")
	}

	return nil
}

func (e DeviceAktif) String() string {
	return string(e)
}
