//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type PesanStatus string

const (
	PesanStatus_MenungguJadwal PesanStatus = "MENUNGGU JADWAL"
	PesanStatus_Gagal          PesanStatus = "GAGAL"
	PesanStatus_Terkirim       PesanStatus = "TERKIRIM"
	PesanStatus_QuotaHabis     PesanStatus = "QUOTA HABIS"
	PesanStatus_Proses         PesanStatus = "PROSES"
	PesanStatus_ProsesDikirim  PesanStatus = "PROSES DIKIRIM"
)

func (e *PesanStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "MENUNGGU JADWAL":
		*e = PesanStatus_MenungguJadwal
	case "GAGAL":
		*e = PesanStatus_Gagal
	case "TERKIRIM":
		*e = PesanStatus_Terkirim
	case "QUOTA HABIS":
		*e = PesanStatus_QuotaHabis
	case "PROSES":
		*e = PesanStatus_Proses
	case "PROSES DIKIRIM":
		*e = PesanStatus_ProsesDikirim
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for PesanStatus enum")
	}

	return nil
}

func (e PesanStatus) String() string {
	return string(e)
}
