//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Sms struct {
	ID          int32 `sql:"primary_key"`
	Sender      string
	Nomor       string
	Pesan       string
	Media       *string
	Status      SmsStatus
	Jadwal      time.Time
	MakeBy      *string
	Time        time.Time
	KodeLembaga string
}
