//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type SmsStatus string

const (
	SmsStatus_MenungguJadwal SmsStatus = "MENUNGGU JADWAL"
	SmsStatus_Gagal          SmsStatus = "GAGAL"
	SmsStatus_Terkirim       SmsStatus = "TERKIRIM"
	SmsStatus_Habis          SmsStatus = "HABIS"
)

func (e *SmsStatus) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "MENUNGGU JADWAL":
		*e = SmsStatus_MenungguJadwal
	case "GAGAL":
		*e = SmsStatus_Gagal
	case "TERKIRIM":
		*e = SmsStatus_Terkirim
	case "HABIS":
		*e = SmsStatus_Habis
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for SmsStatus enum")
	}

	return nil
}

func (e SmsStatus) String() string {
	return string(e)
}
