//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/mysql"
)

var PengajuanAktifView = newPengajuanAktifViewTable("simko_data", "pengajuan_aktif_view", "")

type pengajuanAktifViewTable struct {
	mysql.Table

	// Columns
	NamaAnggota      mysql.ColumnString
	NoIdentitas      mysql.ColumnString
	Alamat           mysql.ColumnString
	KodePengajuan    mysql.ColumnString
	TglPengajuan     mysql.ColumnDate
	NoHp             mysql.ColumnString
	Keterangan       mysql.ColumnString
	Nominal          mysql.ColumnFloat
	NominalDisetujui mysql.ColumnFloat
	KdLembaga        mysql.ColumnString
	KdCabang         mysql.ColumnString
	NoAnggota        mysql.ColumnString
	NoRekening       mysql.ColumnString
	StatusPengajuan  mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type PengajuanAktifViewTable struct {
	pengajuanAktifViewTable

	NEW pengajuanAktifViewTable
}

// AS creates new PengajuanAktifViewTable with assigned alias
func (a PengajuanAktifViewTable) AS(alias string) *PengajuanAktifViewTable {
	return newPengajuanAktifViewTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PengajuanAktifViewTable with assigned schema name
func (a PengajuanAktifViewTable) FromSchema(schemaName string) *PengajuanAktifViewTable {
	return newPengajuanAktifViewTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PengajuanAktifViewTable with assigned table prefix
func (a PengajuanAktifViewTable) WithPrefix(prefix string) *PengajuanAktifViewTable {
	return newPengajuanAktifViewTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PengajuanAktifViewTable with assigned table suffix
func (a PengajuanAktifViewTable) WithSuffix(suffix string) *PengajuanAktifViewTable {
	return newPengajuanAktifViewTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPengajuanAktifViewTable(schemaName, tableName, alias string) *PengajuanAktifViewTable {
	return &PengajuanAktifViewTable{
		pengajuanAktifViewTable: newPengajuanAktifViewTableImpl(schemaName, tableName, alias),
		NEW:                     newPengajuanAktifViewTableImpl("", "new", ""),
	}
}

func newPengajuanAktifViewTableImpl(schemaName, tableName, alias string) pengajuanAktifViewTable {
	var (
		NamaAnggotaColumn      = mysql.StringColumn("nama_anggota")
		NoIdentitasColumn      = mysql.StringColumn("no_identitas")
		AlamatColumn           = mysql.StringColumn("alamat")
		KodePengajuanColumn    = mysql.StringColumn("kode_pengajuan")
		TglPengajuanColumn     = mysql.DateColumn("tgl_pengajuan")
		NoHpColumn             = mysql.StringColumn("no_hp")
		KeteranganColumn       = mysql.StringColumn("keterangan")
		NominalColumn          = mysql.FloatColumn("nominal")
		NominalDisetujuiColumn = mysql.FloatColumn("nominal_disetujui")
		KdLembagaColumn        = mysql.StringColumn("kd_lembaga")
		KdCabangColumn         = mysql.StringColumn("kd_cabang")
		NoAnggotaColumn        = mysql.StringColumn("no_anggota")
		NoRekeningColumn       = mysql.StringColumn("no_rekening")
		StatusPengajuanColumn  = mysql.BoolColumn("status_pengajuan")
		allColumns             = mysql.ColumnList{NamaAnggotaColumn, NoIdentitasColumn, AlamatColumn, KodePengajuanColumn, TglPengajuanColumn, NoHpColumn, KeteranganColumn, NominalColumn, NominalDisetujuiColumn, KdLembagaColumn, KdCabangColumn, NoAnggotaColumn, NoRekeningColumn, StatusPengajuanColumn}
		mutableColumns         = mysql.ColumnList{NamaAnggotaColumn, NoIdentitasColumn, AlamatColumn, KodePengajuanColumn, TglPengajuanColumn, NoHpColumn, KeteranganColumn, NominalColumn, NominalDisetujuiColumn, KdLembagaColumn, KdCabangColumn, NoAnggotaColumn, NoRekeningColumn, StatusPengajuanColumn}
	)

	return pengajuanAktifViewTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		NamaAnggota:      NamaAnggotaColumn,
		NoIdentitas:      NoIdentitasColumn,
		Alamat:           AlamatColumn,
		KodePengajuan:    KodePengajuanColumn,
		TglPengajuan:     TglPengajuanColumn,
		NoHp:             NoHpColumn,
		Keterangan:       KeteranganColumn,
		Nominal:          NominalColumn,
		NominalDisetujui: NominalDisetujuiColumn,
		KdLembaga:        KdLembagaColumn,
		KdCabang:         KdCabangColumn,
		NoAnggota:        NoAnggotaColumn,
		NoRekening:       NoRekeningColumn,
		StatusPengajuan:  StatusPengajuanColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
