//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/mysql"
)

var WhatsappGetTokenLembaga = newWhatsappGetTokenLembagaTable("simko_data", "whatsapp_get_token_lembaga", "")

type whatsappGetTokenLembagaTable struct {
	mysql.Table

	// Columns
	Memberid   mysql.ColumnString
	Nama       mysql.ColumnString
	NoWhatsapp mysql.ColumnString
	Token      mysql.ColumnString
	URL        mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type WhatsappGetTokenLembagaTable struct {
	whatsappGetTokenLembagaTable

	NEW whatsappGetTokenLembagaTable
}

// AS creates new WhatsappGetTokenLembagaTable with assigned alias
func (a WhatsappGetTokenLembagaTable) AS(alias string) *WhatsappGetTokenLembagaTable {
	return newWhatsappGetTokenLembagaTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WhatsappGetTokenLembagaTable with assigned schema name
func (a WhatsappGetTokenLembagaTable) FromSchema(schemaName string) *WhatsappGetTokenLembagaTable {
	return newWhatsappGetTokenLembagaTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WhatsappGetTokenLembagaTable with assigned table prefix
func (a WhatsappGetTokenLembagaTable) WithPrefix(prefix string) *WhatsappGetTokenLembagaTable {
	return newWhatsappGetTokenLembagaTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WhatsappGetTokenLembagaTable with assigned table suffix
func (a WhatsappGetTokenLembagaTable) WithSuffix(suffix string) *WhatsappGetTokenLembagaTable {
	return newWhatsappGetTokenLembagaTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWhatsappGetTokenLembagaTable(schemaName, tableName, alias string) *WhatsappGetTokenLembagaTable {
	return &WhatsappGetTokenLembagaTable{
		whatsappGetTokenLembagaTable: newWhatsappGetTokenLembagaTableImpl(schemaName, tableName, alias),
		NEW:                          newWhatsappGetTokenLembagaTableImpl("", "new", ""),
	}
}

func newWhatsappGetTokenLembagaTableImpl(schemaName, tableName, alias string) whatsappGetTokenLembagaTable {
	var (
		MemberidColumn   = mysql.StringColumn("memberid")
		NamaColumn       = mysql.StringColumn("nama")
		NoWhatsappColumn = mysql.StringColumn("no_whatsapp")
		TokenColumn      = mysql.StringColumn("token")
		URLColumn        = mysql.StringColumn("url")
		allColumns       = mysql.ColumnList{MemberidColumn, NamaColumn, NoWhatsappColumn, TokenColumn, URLColumn}
		mutableColumns   = mysql.ColumnList{MemberidColumn, NamaColumn, NoWhatsappColumn, TokenColumn, URLColumn}
	)

	return whatsappGetTokenLembagaTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Memberid:   MemberidColumn,
		Nama:       NamaColumn,
		NoWhatsapp: NoWhatsappColumn,
		Token:      TokenColumn,
		URL:        URLColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
