//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var AccountAktif = &struct {
	AccountAktif1 mysql.StringExpression
	AccountAktif0 mysql.StringExpression
}{
	AccountAktif1: mysql.NewEnumValue("1"),
	AccountAktif0: mysql.NewEnumValue("0"),
}
