//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var AllContactsType = &struct {
	Personal mysql.StringExpression
	Group    mysql.StringExpression
}{
	Personal: mysql.NewEnumValue("Personal"),
	Group:    mysql.NewEnumValue("Group"),
}
