//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var DeviceAktif = &struct {
	DeviceAktif1 mysql.StringExpression
	DeviceAktif0 mysql.StringExpression
}{
	DeviceAktif1: mysql.NewEnumValue("1"),
	DeviceAktif0: mysql.NewEnumValue("0"),
}
