//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/mysql"

var MysekolahStatus = &struct {
	Reg    mysql.StringExpression
	Aktif  mysql.StringExpression
	Blokir mysql.StringExpression
}{
	Reg:    mysql.NewEnumValue("REG"),
	Aktif:  mysql.NewEnumValue("AKTIF"),
	Blokir: mysql.NewEnumValue("BLOKIR"),
}
