//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Device = newDeviceTable("simko_gateway", "device", "")

type deviceTable struct {
	mysql.Table

	// Columns
	ID          mysql.ColumnInteger
	Pemilik     mysql.ColumnString
	Nomor       mysql.ColumnString
	LinkWebhook mysql.ColumnString
	Aktif       mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type DeviceTable struct {
	deviceTable

	NEW deviceTable
}

// AS creates new DeviceTable with assigned alias
func (a DeviceTable) AS(alias string) *DeviceTable {
	return newDeviceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DeviceTable with assigned schema name
func (a DeviceTable) FromSchema(schemaName string) *DeviceTable {
	return newDeviceTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DeviceTable with assigned table prefix
func (a DeviceTable) WithPrefix(prefix string) *DeviceTable {
	return newDeviceTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DeviceTable with assigned table suffix
func (a DeviceTable) WithSuffix(suffix string) *DeviceTable {
	return newDeviceTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDeviceTable(schemaName, tableName, alias string) *DeviceTable {
	return &DeviceTable{
		deviceTable: newDeviceTableImpl(schemaName, tableName, alias),
		NEW:         newDeviceTableImpl("", "new", ""),
	}
}

func newDeviceTableImpl(schemaName, tableName, alias string) deviceTable {
	var (
		IDColumn          = mysql.IntegerColumn("id")
		PemilikColumn     = mysql.StringColumn("pemilik")
		NomorColumn       = mysql.StringColumn("nomor")
		LinkWebhookColumn = mysql.StringColumn("link_webhook")
		AktifColumn       = mysql.StringColumn("aktif")
		allColumns        = mysql.ColumnList{IDColumn, PemilikColumn, NomorColumn, LinkWebhookColumn, AktifColumn}
		mutableColumns    = mysql.ColumnList{PemilikColumn, NomorColumn, LinkWebhookColumn, AktifColumn}
	)

	return deviceTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Pemilik:     PemilikColumn,
		Nomor:       NomorColumn,
		LinkWebhook: LinkWebhookColumn,
		Aktif:       AktifColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
