//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Nomor = newNomorTable("simko_gateway", "nomor", "")

type nomorTable struct {
	mysql.Table

	// Columns
	ID     mysql.ColumnInteger
	Nama   mysql.ColumnString
	Nomor  mysql.ColumnString
	Pesan  mysql.ColumnString
	MakeBy mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type NomorTable struct {
	nomorTable

	NEW nomorTable
}

// AS creates new NomorTable with assigned alias
func (a NomorTable) AS(alias string) *NomorTable {
	return newNomorTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new NomorTable with assigned schema name
func (a NomorTable) FromSchema(schemaName string) *NomorTable {
	return newNomorTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new NomorTable with assigned table prefix
func (a NomorTable) WithPrefix(prefix string) *NomorTable {
	return newNomorTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new NomorTable with assigned table suffix
func (a NomorTable) WithSuffix(suffix string) *NomorTable {
	return newNomorTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newNomorTable(schemaName, tableName, alias string) *NomorTable {
	return &NomorTable{
		nomorTable: newNomorTableImpl(schemaName, tableName, alias),
		NEW:        newNomorTableImpl("", "new", ""),
	}
}

func newNomorTableImpl(schemaName, tableName, alias string) nomorTable {
	var (
		IDColumn       = mysql.IntegerColumn("id")
		NamaColumn     = mysql.StringColumn("nama")
		NomorColumn    = mysql.StringColumn("nomor")
		PesanColumn    = mysql.StringColumn("pesan")
		MakeByColumn   = mysql.StringColumn("make_by")
		allColumns     = mysql.ColumnList{IDColumn, NamaColumn, NomorColumn, PesanColumn, MakeByColumn}
		mutableColumns = mysql.ColumnList{NamaColumn, NomorColumn, PesanColumn, MakeByColumn}
	)

	return nomorTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:     IDColumn,
		Nama:   NamaColumn,
		Nomor:  NomorColumn,
		Pesan:  PesanColumn,
		MakeBy: MakeByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
