//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Sms = newSmsTable("simko_gateway", "sms", "")

type smsTable struct {
	mysql.Table

	// Columns
	ID          mysql.ColumnInteger
	Sender      mysql.ColumnString
	Nomor       mysql.ColumnString
	Pesan       mysql.ColumnString
	Media       mysql.ColumnString
	Status      mysql.ColumnString
	Jadwal      mysql.ColumnTimestamp
	MakeBy      mysql.ColumnString
	Time        mysql.ColumnTimestamp
	KodeLembaga mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type SmsTable struct {
	smsTable

	NEW smsTable
}

// AS creates new SmsTable with assigned alias
func (a SmsTable) AS(alias string) *SmsTable {
	return newSmsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SmsTable with assigned schema name
func (a SmsTable) FromSchema(schemaName string) *SmsTable {
	return newSmsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SmsTable with assigned table prefix
func (a SmsTable) WithPrefix(prefix string) *SmsTable {
	return newSmsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SmsTable with assigned table suffix
func (a SmsTable) WithSuffix(suffix string) *SmsTable {
	return newSmsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSmsTable(schemaName, tableName, alias string) *SmsTable {
	return &SmsTable{
		smsTable: newSmsTableImpl(schemaName, tableName, alias),
		NEW:      newSmsTableImpl("", "new", ""),
	}
}

func newSmsTableImpl(schemaName, tableName, alias string) smsTable {
	var (
		IDColumn          = mysql.IntegerColumn("id")
		SenderColumn      = mysql.StringColumn("sender")
		NomorColumn       = mysql.StringColumn("nomor")
		PesanColumn       = mysql.StringColumn("pesan")
		MediaColumn       = mysql.StringColumn("media")
		StatusColumn      = mysql.StringColumn("status")
		JadwalColumn      = mysql.TimestampColumn("jadwal")
		MakeByColumn      = mysql.StringColumn("make_by")
		TimeColumn        = mysql.TimestampColumn("time")
		KodeLembagaColumn = mysql.StringColumn("kode_lembaga")
		allColumns        = mysql.ColumnList{IDColumn, SenderColumn, NomorColumn, PesanColumn, MediaColumn, StatusColumn, JadwalColumn, MakeByColumn, TimeColumn, KodeLembagaColumn}
		mutableColumns    = mysql.ColumnList{SenderColumn, NomorColumn, PesanColumn, MediaColumn, StatusColumn, JadwalColumn, MakeByColumn, TimeColumn, KodeLembagaColumn}
	)

	return smsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Sender:      SenderColumn,
		Nomor:       NomorColumn,
		Pesan:       PesanColumn,
		Media:       MediaColumn,
		Status:      StatusColumn,
		Jadwal:      JadwalColumn,
		MakeBy:      MakeByColumn,
		Time:        TimeColumn,
		KodeLembaga: KodeLembagaColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
