//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Account = Account.FromSchema(schema)
	AllContacts = AllContacts.FromSchema(schema)
	Autoreply = Autoreply.FromSchema(schema)
	Contacts = Contacts.FromSchema(schema)
	Device = Device.FromSchema(schema)
	Nomor = Nomor.FromSchema(schema)
	Pesan = Pesan.FromSchema(schema)
	Sms = Sms.FromSchema(schema)
	SmsInbox = SmsInbox.FromSchema(schema)
}
